-
  - /iphone
  - handlers.iphone
-
  - /about
  - handlers.about
-
  - /search/edits
  - handlers.search.edits
-
  - /search
  - handlers.search.default
-
  - /sites
  - handlers.sites.default
-
  - /sites/([^/]+)
  - handlers.sites.detail
-
  - /sites/([^/]+)/open
  - handlers.sites.open
-
  - /sites/([^/]+)/closed
  - handlers.sites.closed
-
  - /sites/([^/]+)/edits/([^/]+)/close
  - handlers.sites.edits.close
-
  - /sites/([^/]+)/edits/([^/]+)
  - handlers.sites.edits.detail
-
  - /sites/([^/]+)/edits/([^/]+)/open
  - handlers.sites.edits.open
-
  - /sites/([^/]+)/edits/([^/]+)/pingback
  - handlers.sites.edits.pingback
-
  - /sites/([^/]+)/edits/([^/]+)/test
  - handlers.sites.edits.test
-
  - /sites/([^/]+)/edits/([^/]+)/trackback
  - handlers.sites.edits.trackback
-
  - /sites/([^/]+)/edits/([^/]+)/update
  - handlers.sites.edits.update
-
  - /sites/([^/]+)/edits/([^/]+)/delete
  - handlers.sites.edits.delete
-
  - /tasks/edits/test
  - handlers.tasks.edits.test
-
  - /users
  - handlers.users.default
-
  - /users/([^/]+)
  - handlers.users.detail
-
  - /users/([^/]+)/closed
  - handlers.users.closed
-
  - /users/([^/]+)/open
  - handlers.users.open
-
  - /users/([^/]+)/nickname
  - handlers.users.nickname
-
  - /widgets
  - handlers.widgets
-
  - /*
  - handlers.default
-
  - /.*
  - handlers.not_found
