application: emend
version: 1
runtime: python
api_version: 1

default_expiration: "10d"

builtins:
- remote_api: on

handlers:
- url: /css
  static_dir: static/css
  
- url: /js
  static_dir: static/js
  
- url: /images
  static_dir: static/images

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /LICENSE
  static_files: LICENSE
  upload: LICENSE
  mime_type: text/plain; charset=utf-8

- url: /test.*
  script: gaeunit.py

- url: /console.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: .*
  script: main.py
