-
  - /iphone
  - handlers.iphone
-
  - /about
  - handlers.about
-
  - /search/edits
  - handlers.search.edits
-
  - /search
  - handlers.search.default
-
  - /sites
  - handlers.sites.default
-
  - /sites/([^/]+?)
  - handlers.sites.detail
-
  - /sites/([^/]+)/open
  - handlers.sites.open
-
  - /sites/([^/]+)/closed
  - handlers.sites.closed
-
  - /sites/([^/]+)/edits/([^/]+)/close
  - handlers.sites.edits.close
-
  - /sites/([^/]+)/edits/([\d]+)
  - handlers.sites.edits.detail
-
  - /sites/([^/]+)/edits/([\d]+)/open
  - handlers.sites.edits.open
-
  - /sites/([^/]+)/edits/([\d]+)/pingback
  - handlers.sites.edits.pingback
-
  - /sites/([^/]+)/edits/([\d]+)/test
  - handlers.sites.edits.test
-
  - /sites/([^/]+)/edits/([\d]+)/trackback
  - handlers.sites.edits.trackback
-
  - /sites/([^/]+)/edits/([\d]+)/update
  - handlers.sites.edits.update
-
  - /sites/([^/]+)/edits/([\d]+)/delete
  - handlers.sites.edits.delete
-
  - /tasks/edits/test
  - handlers.tasks.edits.test
-
  - /users
  - handlers.users.default
-
  - /users/([^/]+?)
  - handlers.users.detail
-
  - /users/([^/]+)/closed
  - handlers.users.closed
-
  - /users/([^/]+)/open
  - handlers.users.open
-
  - /users/([^/]+)/nickname
  - handlers.users.nickname
-
  - /users/([^/]+)/ban
  - handlers.users.ban
-
  - /users/([^/]+)/unban
  - handlers.users.unban
-
  - /widgets
  - handlers.widgets
-
  - /sections/diff
  - handlers.sections.diff
-
  - /*
  - handlers.default
-
  - /.*
  - handlers.not_found
