-
  - /iphone
  - handlers.iphone
-
  - /about
  - handlers.about
-
  - /jetpack
  - handlers.jetpack
-
  - /admin/edit
  - handlers.admin.edit
-
  - /admin/memclear
  - handlers.admin.memclear
-
  - /admin/site_count
  - handlers.admin.site_count
-
  - /admin/site_key
  - handlers.admin.site_key
-
  - /admin/user_count
  - handlers.admin.user_count
-
  - /admin/user_key
  - handlers.admin.user_key
-
  - /search/edits
  - handlers.search.edits
-
  - /search
  - handlers.search.default
-
  - /sites
  - handlers.sites.default
-
  - /sites/([^/]+)
  - handlers.sites.detail
-
  - /sites/([^/]+)/edits/([^/]+)/close
  - handlers.sites.edits.close
-
  - /sites/([^/]+)/edits/([^/]+)
  - handlers.sites.edits.detail
-
  - /sites/([^/]+)/edits/([^/]+)/open
  - handlers.sites.edits.open
-
  - /sites/([^/]+)/edits/([^/]+)/pingback
  - handlers.sites.edits.pingback
-
  - /sites/([^/]+)/edits/([^/]+)/test
  - handlers.sites.edits.test
-
  - /sites/([^/]+)/edits/([^/]+)/trackback
  - handlers.sites.edits.trackback
-
  - /sites/([^/]+)/edits/([^/]+)/update
  - handlers.sites.edits.update
-
  - /sites/([^/]+)/edits/([^/]+)/delete
  - handlers.sites.edits.delete
-
  - /tasks/edits/test
  - handlers.tasks.edits.test
-
  - /users
  - handlers.users.default
-
  - /users/([^/]+)
  - handlers.users.detail
-
  - /users/([^/]+)/closed
  - handlers.users.closed
-
  - /users/([^/]+)/open
  - handlers.users.open
-
  - /users/([^/]+)/nickname
  - handlers.users.nickname
-
  - /*
  - handlers.default
-
  - /.*
  - handlers.not_found
